// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzn5LV_jk2TAKDK60Q8bnG5YSL_uEaUVI',
    appId: '1:1088338713221:web:your_web_app_id',
    messagingSenderId: '1088338713221',
    projectId: 'growfirst-f01b0',
    authDomain: 'growfirst-f01b0.firebaseapp.com',
    storageBucket: 'growfirst-f01b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzn5LV_jk2TAKDK60Q8bnG5YSL_uEaUVI',
    appId: '1:1088338713221:android:96968d11fc541c322127ec',
    messagingSenderId: '1088338713221',
    projectId: 'growfirst-f01b0',
    storageBucket: 'growfirst-f01b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoH23GBVMJZAxQzUt9ZwXUdOaloJaC4m4',
    appId: '1:1088338713221:ios:a6ad56212e3317fe2127ec',
    messagingSenderId: '1088338713221',
    projectId: 'growfirst-f01b0',
    storageBucket: 'growfirst-f01b0.firebasestorage.app',
    iosBundleId: 'com.growfirst.app.growFirst',
  );
}
